# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa6646d5339a0bb96cb228e24d44f8f29867e56e63ba4fe1f403cc37126e076cb0ecccdbad3e8c9614fe1a27607e78f6f990680aef5997608280b1e423405007

test:
  secret_key_base: 72d5c0b41bd43117d5b5bd40b5306292564d1b1dde01df154a682c68955a210f78534126ab196137e4ca40f9ed2e505f2616359bcd3e34180e2b84cee1602045

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
